server:
  port: 8001
  servlet:
    context-path: /client-provider

spring:
  application:
    name: client-provider

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10101/eureka

xxx: test