# 基础配置
server:
  port: 22222
  servlet:
    context-path: /server-config

# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11111/eureka
  instance:
    metadata-map:
      configPath: ${server.servlet.context-path}

spring:
  application:
    name: server-config
  # 配置中心
  cloud:
    config:
      server:
        git:
          uri: https://github.com/20gongzi/demo-project-config.git
          default-label: main
          search-paths: /**
  # 消息总线
  rabbitmq:
    host: 192.168.11.101
    username: guest
    password: guest
    virtual-host: /

# 安全监控
management:
  endpoints:
    web:
      exposure:
        include: refresh,bus-refresh,health,info