# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11111/eureka
# 基础配置
server:
  port: 7001
  servlet:
    context-path: /client-config
# 服务配置
spring:
  application:
    name: client-config
  # 消息总线
  rabbitmq:
    host: 192.168.11.128
    username: guest
    password: guest
    virtual-host: /
# 安全监控
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,refresh,health,info

xxx: test