server:
  port: 8001
  servlet:
    context-path: /client-config

spring:
  application:
    name: client-config

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11111/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,health

xxx: dev