server:
  port: 7001
  servlet:
    context-path: /client-config

spring:
  application:
    name: client-config

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10101/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh,health

xxx: test