server:
  port: 8001
  servlet:
    context-path: /client-config

spring:
  application:
    name: client-config

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10101/eureka

xxx: dev update